var maoriMyth = ["Papatuānuku", 
"Ranginui", 
"Tawhirimatea", 
"Ruaumoko", 
"Hineahuone", 
"Hinenuitepō",
"Maui me te Ra", 
"Te Ika a Maui", 
"Māui rāua ko Mahuika", 
"Ngake rāua ko Whātaitai", 
"Tūrehu", 
"Patupaiarehe", 
"Hinewhaitiri", 
"Kupe", 
"Io", 
"Paikea", 
"Kupe", 
"Rongokako", 
"Horowhatu", 
"Hikurangi", 
"Kurangaituku"];
