var maoriMyth = [
"Papatuanuku", 
"Ranginui", 
"Tawhirimatea", 
"Ruaumoko", 
"Hineahuone", 
"Hinenuitepo",
"Maui me te Ra", 
"Te Ika a Maui", 
"Maui raua ko Mahuika", 
"Ngake rāua ko Whataitai", 
"Turehu", 
"Patupaiarehe", 
"Hinewhaitiri", 
"Kupe", 
"Io", 
"Paikea", 
"Kupe", 
"Rongokako", 
"Horowhatu", 
"Hikurangi", 
"Kurangaituku"];

var movies = [
"Boy",
"What we do in the shadows",
"Hunt for the Wilderpeople",
"Once Were Warriors",
"What Becomes of the Broken Hearted",
"The Whale Rider",
"Mahana",
"Ngati",
"Goodby Pork Pie",
"The Orator",
"The Dark Horse",
"Utu",
"The Deadlands",
"Two Cars, One Night",
"Crooked Earth",
"Eagle vs Shark",
"Born to Dance",
"Sione's Wedding",
"Samoan Wedding",
"The Pa Boys",
"Footrot Flats: The Dog's Tail",
"Tama Tu",
"The Sixty Dollar Fifty Man",
"Scarfies"]

var songs = [
"Ten Guitars",
"Poi E, Patea Maori Club",
"Don't Dream Its Over, Crowded House",
"Aotearoa, Stan Walker",
"Take It Easy, Stan Walker",
"Melting Pot",
"Slice of Heaven, Dave Dobbyn",
"Welcome Home, Dave Dobbyn",
"Ponga Ra, Rob Ruha",
"Tangaroa Whakamautai, Maisey Rika",
"Royals, Lorde",
"Whitiora, Maisey Rika",
"Maumahara Noa, Brannigan Kaa",
]