var maoriMyth = [
"Papatuānuku", 
"Ranginui", 
"Tawhirimatea", 
"Ruaumoko", 
"Hineahuone", 
"Hinenuitepō",
"Maui me te Ra", 
"Te Ika a Maui", 
"Māui rāua ko Mahuika", 
"Ngake rāua ko Whātaitai", 
"Tūrehu", 
"Patupaiarehe", 
"Hinewhaitiri", 
"Kupe", 
"Io", 
"Paikea", 
"Kupe", 
"Rongokako", 
"Horowhatu", 
"Hikurangi", 
"Kurangaituku"];

var movies = [
"Boy",
"What we do in the shadows",
"Hunt for the Wilderpeople",
"Once Were Warriors",
"What Becomes of the Broken Hearted",
"The Whale Rider",
"Mahana",
"Ngati",
"Goodby Pork Pie",
"The Orator",
"The Dark Horse",
"Utu",
"The Deadlands",
"Two Cars, One Night",
"Crooked Earth",
"Eagle vs Shark",
"Born to Dance",
"Sione's Wedding",
"Samoan Wedding",
"The Pa Boys",
"Footrot Flats: The Dog's Tail",
"Tama Tu",
"The Sixty Dollar Fifty Man",
"Scarfies"]
